#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/manifest.v2.schema.json

packaging_format = 2

id = "plant-it"
name = "Plant-it"
description.en = "🪴 Gardening companion app"
description.fr = "🪴 Compagnon de plantation"

version = "0.10.0~ynh1"

maintainers = ["Thovi98"]

[upstream]
license = "GPL-3.0"
website = "https://plant-it.org/"
admindoc = "https://docs.plant-it.org/0.9.0/"
userdoc = "https://docs.plant-it.org/0.9.0/features/"
code = "https://github.com/MDeLuise/plant-it"
fund = "https://buymeacoffee.com/mdeluise"

[integration]
yunohost = ">= 12.0.0"
helpers_version = "2.1"
architectures = "all"
multi_instance = true

ldap = false
sso = false

disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.path]
    type = "path"
    default = "/example"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

    [install.admin]
    type = "user"

    [install.password]
    type = "password"

    [install.floracodex_api_key]
    ask.en = "(Optional) Insert here the api key from the FLORACODEX api key"
    type = "string"
    default = false
    optional = true

[resources]

    [resources.sources]

    [resources.sources.frontend]
    url = "https://github.com/MDeLuise/plant-it/releases/download/0.10.0/client.tar.gz"
    sha256 = "7df35332b1f36a55b27488d84bd0a885707edf7c472bcc3a098031d206739aae"

    autoupdate.strategy = "latest_github_release"
    autoupdate.asset = "client.tar.gz"

    [resources.sources.backend]
    url = "https://github.com/MDeLuise/plant-it/releases/download/0.10.0/server.jar"
    sha256 = "445fb2f85455f48106a3bf5c696f17feb31414745a80efa26ffd735b42d244c2"

    autoupdate.strategy = "latest_github_release"
    autoupdate.asset = "server.jar"

    [resources.sources.jdk]
    amd64.url = "https://github.com/adoptium/temurin21-binaries/releases/download/jdk-21.0.5%2B11/OpenJDK21U-jdk_x64_linux_hotspot_21.0.5_11.tar.gz"
    amd64.sha256 = "3c654d98404c073b8a7e66bffb27f4ae3e7ede47d13284c132d40a83144bfd8c"
    arm64.url = "https://github.com/adoptium/temurin21-binaries/releases/download/jdk-21.0.5%2B11/OpenJDK21U-jdk_aarch64_linux_hotspot_21.0.5_11.tar.gz"
    arm64.sha256 = "6482639ed9fd22aa2e704cc366848b1b3e1586d2bf1213869c43e80bca58fe5c"
    
    autoupdate.strategy = "latest_github_release"
    autoupdate.version_regex = "jdk-(\\d+\\.\\d+\\.\\d+)\\+(.*)"
    autoupdate.upstream = "https://github.com/adoptium/temurin21-binaries"
    autoupdate.asset.amd64 = "OpenJDK.*-jdk_x64_linux_hotspot_.*\\.tar\\.gz$"
    autoupdate.asset.arm64 = "OpenJDK.*-jdk_aarch64_linux_hotspot_.*\\.tar\\.gz$"

    [resources.system_user]
    allow_email = true

    [resources.install_dir]

    [resources.data_dir]

    [resources.permissions]
    main.url = "/"

    [resources.ports]
    backend.default = 8080
    frontend.default = 3000

    [resources.database]
    type = "mysql"
